# 이 파일은 작업지시서(workflow)임
# - 언제(on) => "main에 push 하면"
# - 작업(jobs) => 할 일 목록
# - Build :
#       어디서 : 깃허브 서버 컴퓨터에서 (runner)
#         단계 : 1. 코드 가져와 -> 2. 빌드해

# 1. 작업지시서 이름
name: Unity WebGL Build

# 2. 언제 실행할 것인가? (이벤트, 트리거, on)
on:
  push:
    branches: [main]

# 3. 무엇을?
jobs:
  build:
    # 3-1 어디서 실행할 것인가? - 리눅스 ubuntu
    runs-on: ubuntu-latest
    
    # 3-2 실행할 단계
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Build in Unity
        run: echo "Run Unity Build."